### ISSUE TITLE
ValueError while running with docker compose

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [Linus2punkt0/bluesky-crossposter#75]
I get the following error when trying to use the included `docker-compose.yml`:
```
WARN[0000] /home/madmax/bin/bluesky-crossposter/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/0
 ✔ Container bluesky-crossposter-crossposter-1  Recreated                  0.0s 
Attaching to crossposter-1
crossposter-1  | Traceback (most recent call last):
crossposter-1  |   File "//crosspost.py", line 4, in <module>
crossposter-1  |     from local.functions import cleanup, post_cache_read, post_cache_write, get_post_time_limit, check_rate_limit, logger
crossposter-1  |   File "/local/functions.py", line 6, in <module>
crossposter-1  |     from settings import settings
crossposter-1  |   File "/settings/settings.py", line 71, in <module>
crossposter-1  |     overflow_posts = int(os.environ.get('OVERFLOW_POST')) if os.environ.get('OVERFLOW_POST') else overflow_posts
crossposter-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crossposter-1  | ValueError: invalid literal for int() with base 10: 'retry'
```
The environment variables are included within the `docker-compose.yml`-file, the value of OVERFLOW_POST is `OVERFLOW_POST: "retry"`, as stated in the `settings.py`-file

What's up?

**Comment by cyberpunkrocker-zero** [comment]
And here's the whole `docker-compose.yml`-file (personal information redacted)
```
version: '3.8'
services:
  crossposter:
    build: .
    restart: always
    environment:
      BSKY_HANDLE: "xxx"
      BSKY_PASSWORD: "xxx"
      MASTODON_HANDLE: "xxx"
      MASTODON_INSTANCE: "xxx"
      MASTODON_TOKEN: "xxx"
      TWITTER_APP_KEY:
      TWITTER_APP_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
      # defaults to true, change to false if you don't want to enable it
      TWITTER_CROSSPOSTING: ${TWITTER_CROSSPOSTING:-false}
      MASTODON_CROSSPOSTING: ${MASTODON_CROSSPOSTING:-true}
      LOG_LEVEL:
      MASTODON_VISIBILITY: "hybrid"
      MENTIONS: "strip"
      POST_DEFAULT: "true"
      MASTODON_LANG:
      TWITTER_LANG:
      QUOTE_POSTS: "true"
      MAX_RETRIES: "5"
      POST_TIME_LIMIT: "1"
      MAX_PER_HOUR: "0"
      OVERFLOW_POST: "retry"
      # job interval, defaults to 1 hour(the max lag between bluesky and twitter/mastodon)
      RUN_INTERVAL: ${RUN_INTERVAL:-600}
    volumes:
      - ./dbhost:/db
      - ./backup:/backup
```
Is there something wrong with it?
